### ISSUE TITLE
PARSE_NODEGOAT_DATE

### ISSUE THREAD

**Issue by akidonakis-ims** [nodegoat/nodegoat#15]
FUNCTION nodegoat_temp.PARSE_NODEGOAT_DATE does not exist;

I cannot see in the source where this function is created.
nodegoat_temp is empty. Without any functions or tables for that matter.

**Comment by LAB1100** [comment]
We've updated SETUP to make sure the function you're referring to will appear, as it's a result of the instructions.

https://github.com/nodegoat/nodegoat/commit/3dbe025934eca9b4d443cfc48e21003fcc17d264

**Comment by akidonakis-ims** [comment]
Thanks for the quick repsonse.

I had ran all the jobs manually at least once.
After clearing the logs and running the job again again, I noticed the following message in the logs.
You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)

the solution was to set the mysql paramter log_bin_trust_function_creators = 1 

mysql> SET GLOBAL log_bin_trust_function_creators = 1;

or edit my.cnf under 
[mysqld]
log_bin_trust_function_creators = 1

see: https://dev.mysql.com/doc/refman/8.0/en/stored-programs-logging.html
