### ISSUE TITLE
Conditions - node icons

### ISSUE THREAD

**Issue by hblomme** [nodegoat/nodegoat#3]
Het lukt wel om een svg-icoon op te laden bij conditions - nodes, maar in de visualisaties worden deze iconen vervolgens niet weergegeven.

**Comment by LAB1100** [comment]
Custom SVG icons are supported in the geographic visualisation at the moment.

What Visual Settings display mode are you using (vector or pixel)?

**Comment by hblomme** [comment]
We want to create a social visualization. We are using the 'vector' visual settings display mode.

**Comment by LAB1100** [comment]
This feature is only available for the geographic visualisation at the moment. We will reopen this issue once this has been made available in the social visualisation.
